package com.pranav.driveportal.userAuthapp.services;

import java.sql.Date;

import org.springframework.stereotype.Service;

import com.pranav.driveportal.userAuthapp.proxy.FeignClientforCreate5folders;

@Service
public class UserSerivce implements UserSericeInteface{
	
	
	private final JdbcDatabase allPurposeInstance;
	private final FeignClientforCreate5folders create5folds;
	
	public UserSerivce(JdbcDatabase signUpinst, FeignClientforCreate5folders create5folds) {
		super();
		this.allPurposeInstance = signUpinst;
		this.create5folds = create5folds;
	}

	@Override
	public String addUserSignUp(String userName, String Password, String mailId, Long phoneno,Date dob) throws Exception {
		
		String autoGeneratedUname =  allPurposeInstance.signUP(userName, Password, mailId, phoneno, dob);
		String temp = create5folds.create5FoldersafterSignup(autoGeneratedUname);
		
		return autoGeneratedUname;
	}

	@Override
	public Boolean fetchUserLogin(String userName, String Password) {
		
		Boolean res=false;
		try {
			res = allPurposeInstance.signIN(userName, Password);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return res;
	}

	@Override
	public String forgotUnameorPass(String mailid) {
		
		try {
			if(!allPurposeInstance.fetchEmail(mailid)) {
				return "";
			}
			else {
				String newPass = allPurposeInstance.changePass(mailid);
				return newPass;
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return "";
	}
	
	

}
